language: ruby
rvm: 3.1.0
sudo: required
dist: focal
cache:
  apt: true
  directories:
  - vendor
  - node_modules
addons:
  mariadb: '10.5' # we use 10.3 in production, but installation of 10.3 has been broken on travis
  chrome: stable
  apt:
    packages:
    - pandoc
services:
  - redis-server
before_install:
- rvm --default use 3.1.0
- nvm install # use Node version specified in .nvmrc
- export PATH=$PATH:`yarn global bin`
- export DB=test
- export SENDER_EMAIL_ADDRESS='sender@wikiedu.org'
- node --version
- yarn --version
install:
- yarn install
- gem update --system
- gem install bundler
- gem install rubocop
- gem install rubocop-rspec-focused
- bundle install --jobs=3 --retry=3 --deployment
before_script:
- mkdir tmp -m 777
- cp config/database.travis.yml config/database.yml
- sudo mysql -e "SET Password=PASSWORD('rootpassword')"
- sudo mysql -e "CREATE DATABASE test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
- bundle exec rake db:migrate RAILS_ENV=test
script:
  - yarn build
  - yarn test
  - COVERAGE=true bundle exec rspec --color --profile --format documentation
  - bundle exec rubocop
  - yarn lint-non-build
after_success:
- "./travis-deploy-staging.sh"
